# Generated by Django 6.0.4 on 2026-05-07 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('min_items', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de veces que se puede completar este grupo (todos sus campos).', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_items', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de veces que se puede completar este grupo. Puede dejarse vacío si no hay límite.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_repeatable', models.BooleanField(default=False, help_text='Indica si este grupo puede repetirse múltiples veces.')),
                ('question', models.ForeignKey(help_text='Pregunta a la que pertenece este grupo.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='question_bank.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('date', 'Date'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('select', 'Select'), ('boolean', 'Boolean')], help_text='Tipo de campo que define el comportamiento del input.', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Indica si este campo es obligatorio.')),
                ('option_source', models.CharField(blank=True, choices=[('db', 'Database'), ('countries', 'Countries Library'), ('us_states', 'US States Catalog')], default='', help_text='Fuente de datos para las opciones en campos tipo select.', max_length=20)),
                ('group', models.ForeignKey(help_text='Grupo al que pertenece este campo.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='question_bank.questiongroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('value', models.CharField(help_text='Valor que representa esta opción para el usuario.', max_length=255)),
                ('field', models.ForeignKey(help_text='Campo al que pertenece esta opción.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question_bank.groupfield')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('field', 'order'), name='unique_active_option_order_per_field')],
            },
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'order'), name='unique_active_group_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='groupfield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'order'), name='unique_active_field_order_per_group'),
        ),
    ]
