# Generated by Django 6.0.4 on 2026-05-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfield',
            name='is_required',
        ),
    ]
