# Generated by Django 6.0.4 on 2026-04-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_engine.formtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form_template', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('boolean', 'Boolean')], max_length=20)),
                ('option_source', models.CharField(choices=[('none', 'None'), ('db', 'Database'), ('countries', 'Countries Library'), ('us_states', 'US States Catalog')], default='none', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_engine.formsection')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
