# Generated by Django 6.0.4 on 2026-04-29 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(help_text="Código único de la plantilla dentro de USCIS. Ej: 'I-589'.", max_length=50, unique=True)),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta plantilla está activa.')),
            ],
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('key', models.CharField(help_text="Identificador interno (no visible al usuario). Ej: 'personal_data'.", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('date', 'Date'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('select', 'Select'), ('boolean', 'Boolean')], help_text='Tipo de campo que define el comportamiento del input.', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Indica si este campo es obligatorio.')),
                ('option_source', models.CharField(blank=True, choices=[('db', 'Database'), ('countries', 'Countries Library'), ('us_states', 'US States Catalog')], default='', help_text='Fuente de datos para las opciones en campos tipo select.', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('key', models.CharField(help_text="Identificador interno (no visible al usuario). Ej: 'personal_data'.", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('is_repeatable', models.BooleanField(default=False, help_text='Indica si este grupo puede repetirse múltiples veces.')),
                ('min_items', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de veces que se puede completar este grupo (todos sus campos).', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_items', models.PositiveIntegerField(default=1, help_text='Cantidad máxima de veces que se puede completar este grupo (todos sus campos). Puede dejarse vacío si no hay límite.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_required', models.BooleanField(default=False, help_text='Indica si este grupo es obligatorio.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('key', models.CharField(help_text="Identificador interno (no visible al usuario). Ej: 'personal_data'.", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('is_required', models.BooleanField(default=False, help_text='Indica si esta sección es obligatoria dentro de la plantilla.')),
                ('form_template', models.ForeignKey(help_text='Plantilla a la que pertenece esta sección.', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='forms_engine.formtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('key', models.CharField(help_text="Identificador interno (no visible al usuario). Ej: 'personal_data'.", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('value', models.CharField(help_text='Valor que representa esta opción para el usuario.', max_length=255)),
                ('field', models.ForeignKey(help_text='Campo al que pertenece esta opción.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms_engine.groupfield')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='groupfield',
            name='group',
            field=models.ForeignKey(help_text='Grupo al que pertenece este campo.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.questiongroup'),
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texto visible para el usuario. Se mostrará como título o pregunta en la interfaz.', max_length=255)),
                ('key', models.CharField(help_text="Identificador interno (no visible al usuario). Ej: 'personal_data'.", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Define si este elemento está activo y debe ser utilizado.')),
                ('order', models.PositiveIntegerField(help_text='Define la posición de este elemento dentro de su grupo.', validators=[django.core.validators.MinValueValidator(1, message='El orden mínimo permitido es 1.')])),
                ('is_required', models.BooleanField(default=False, help_text='Indica si esta pregunta es obligatoria.')),
                ('section', models.ForeignKey(help_text='Sección a la que pertenece esta pregunta.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_engine.formsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='question',
            field=models.ForeignKey(help_text='Pregunta a la que pertenece este grupo.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='forms_engine.sectionquestion'),
        ),
        migrations.AddConstraint(
            model_name='formsection',
            constraint=models.UniqueConstraint(fields=('form_template', 'key'), name='unique_section_key_per_form'),
        ),
        migrations.AddConstraint(
            model_name='formsection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('form_template', 'order'), name='unique_active_section_order_per_form'),
        ),
        migrations.AddConstraint(
            model_name='fieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'key'), name='unique_option_key_per_field'),
        ),
        migrations.AddConstraint(
            model_name='fieldoption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('field', 'order'), name='unique_active_option_order_per_field'),
        ),
        migrations.AddConstraint(
            model_name='groupfield',
            constraint=models.UniqueConstraint(fields=('group', 'key'), name='unique_field_key_per_group'),
        ),
        migrations.AddConstraint(
            model_name='groupfield',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'order'), name='unique_active_field_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='sectionquestion',
            constraint=models.UniqueConstraint(fields=('section', 'key'), name='unique_question_key_per_section'),
        ),
        migrations.AddConstraint(
            model_name='sectionquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'order'), name='unique_active_question_order_per_section'),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(fields=('question', 'key'), name='unique_group_key_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'order'), name='unique_active_group_order_per_question'),
        ),
    ]
