# Generated by Django 6.0.4 on 2026-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtemplate',
            old_name='code',
            new_name='form_code',
        ),
    ]
